#include "reticlex/rx_math.h"

/*
 * These routines are deliberately hand written rather than delegated to libm.
 * Geometry produced by the MSVC DLL build is compared against golden fixtures
 * generated by the clang wasm build, so every arithmetic step has to be
 * bit-reproducible across toolchains. Exact-rational Taylor coefficients and
 * explicit range reduction give us that; a vendor libm would not.
 */

typedef union { float f; unsigned int i; } rx_f32_bits;

float rx_absf(float x) { return x < 0.0f ? -x : x; }

float rx_minf(float a, float b) { return a < b ? a : b; }
float rx_maxf(float a, float b) { return a > b ? a : b; }

float rx_clampf(float x, float lo, float hi) {
    if (!rx_is_finite(x)) return lo;
    if (x < lo) return lo;
    if (x > hi) return hi;
    return x;
}

int rx_clampi(int x, int lo, int hi) {
    if (x < lo) return lo;
    if (x > hi) return hi;
    return x;
}

float rx_lerpf(float a, float b, float t) { return a + (b - a) * t; }

int rx_is_finite(float x) {
    rx_f32_bits u;
    u.f = x;
    return ((u.i >> 23) & 0xFFu) != 0xFFu;
}

float rx_floorf(float x) {
    if (!rx_is_finite(x)) return 0.0f;
    /* Beyond 2^23 every float is already integral. */
    if (x >= 8388608.0f || x <= -8388608.0f) return x;
    float t = (float)(int)x;
    return (t > x) ? t - 1.0f : t;
}

float rx_ceilf(float x) {
    float f = rx_floorf(x);
    return (f < x) ? f + 1.0f : f;
}

float rx_roundf(float x) {
    return (x >= 0.0f) ? rx_floorf(x + 0.5f) : -rx_floorf(-x + 0.5f);
}

float rx_fmodf(float x, float y) {
    if (y == 0.0f || !rx_is_finite(x) || !rx_is_finite(y)) return 0.0f;
    float q = x / y;
    /* Truncate toward zero, matching C's fmod sign convention. */
    float t = (q >= 0.0f) ? rx_floorf(q) : rx_ceilf(q);
    return x - t * y;
}

float rx_wrapf(float x, float lo, float hi) {
    float span = hi - lo;
    if (span <= 0.0f || !rx_is_finite(x)) return lo;
    float r = rx_fmodf(x - lo, span);
    if (r < 0.0f) r += span;
    return lo + r;
}

float rx_sqrtf(float x) {
    if (!(x > 0.0f) || !rx_is_finite(x)) return 0.0f;
    /* Halve the exponent for a ~5% accurate seed, then Newton-Raphson. */
    rx_f32_bits u;
    u.f = x;
    u.i = 0x1FBD1DF5u + (u.i >> 1);
    float y = u.f;
    y = 0.5f * (y + x / y);
    y = 0.5f * (y + x / y);
    y = 0.5f * (y + x / y);
    return y;
}

/* Degree-11 odd Taylor series, exact after reduction onto [0, pi/2]. */
static float rx_sin_core(float x) {
    float x2 = x * x;
    float y = -1.0f / 39916800.0f;      /* -1/11! */
    y = y * x2 + 1.0f / 362880.0f;      /*  1/9!  */
    y = y * x2 - 1.0f / 5040.0f;        /* -1/7!  */
    y = y * x2 + 1.0f / 120.0f;         /*  1/5!  */
    y = y * x2 - 1.0f / 6.0f;           /* -1/3!  */
    return x + x * x2 * y;
}

float rx_sinf(float x) {
    if (!rx_is_finite(x)) return 0.0f;
    x = rx_wrapf(x, -RX_PI, RX_PI);
    float sign = 1.0f;
    if (x < 0.0f) { x = -x; sign = -1.0f; }
    if (x > RX_HALF_PI) x = RX_PI - x;
    return sign * rx_sin_core(x);
}

float rx_cosf(float x) { return rx_sinf(x + RX_HALF_PI); }

float rx_logf(float x) {
    if (!(x > 0.0f) || !rx_is_finite(x)) return 0.0f;
    /* x = m * 2^e with m in [sqrt(0.5), sqrt(2)). */
    rx_f32_bits u;
    u.f = x;
    int e = (int)((u.i >> 23) & 0xFFu) - 127;
    u.i = (u.i & 0x007FFFFFu) | 0x3F800000u;   /* mantissa into [1, 2) */
    float m = u.f;
    if (m > 1.41421356f) { m *= 0.5f; e += 1; }
    /* atanh series: log(m) = 2 * sum s^(2k+1)/(2k+1), s = (m-1)/(m+1). */
    float s = (m - 1.0f) / (m + 1.0f);
    float s2 = s * s;
    float y = 1.0f / 9.0f;
    y = y * s2 + 1.0f / 7.0f;
    y = y * s2 + 1.0f / 5.0f;
    y = y * s2 + 1.0f / 3.0f;
    y = y * s2 + 1.0f;
    return 2.0f * s * y + (float)e * 0.69314718055994530942f;
}

float rx_expf(float x) {
    if (!rx_is_finite(x)) return 0.0f;
    if (x > 88.0f) return 3.4028235e38f;
    if (x < -88.0f) return 0.0f;
    /* x = k*ln2 + r, |r| <= ln2/2. */
    float kf = rx_roundf(x * 1.44269504088896340736f);
    int k = (int)kf;
    float r = x - kf * 0.69314718055994530942f;
    float y = 1.0f / 5040.0f;
    y = y * r + 1.0f / 720.0f;
    y = y * r + 1.0f / 120.0f;
    y = y * r + 1.0f / 24.0f;
    y = y * r + 1.0f / 6.0f;
    y = y * r + 0.5f;
    y = y * r + 1.0f;
    y = y * r + 1.0f;
    /* Scale by 2^k by writing the exponent field directly. */
    rx_f32_bits u;
    u.i = (unsigned int)((k + 127) & 0xFF) << 23;
    return y * u.f;
}

float rx_powf(float base, float exponent) {
    if (exponent == 0.0f) return 1.0f;
    if (base == 0.0f) return 0.0f;
    if (base < 0.0f) return 0.0f;   /* Callers only ever raise non-negative values. */
    return rx_expf(exponent * rx_logf(base));
}
