/*
 * Emits the golden geometry fixtures shared with the JavaScript test suite.
 *
 * The front end talks to a wasm build of this same core, so the fixtures prove
 * that the native library and the wasm module resolve identical geometry from
 * identical configuration. Run via scripts/build-core.sh.
 */
#include "reticlex/api.h"

#include <cstdio>
#include <cstring>
#include <string>
#include <vector>

namespace {

struct Case {
    const char *name;
    rx_config config;
};

/* Writes the config as its flat field sequence, consulting the core's own
   field table so integral members are never printed as denormal floats. */
void write_config(std::string &out, const rx_config &c) {
    const unsigned char *bytes = reinterpret_cast<const unsigned char *>(&c);
    char buffer[64];
    out += "[";
    for (int i = 0; i < RX_CONFIG_FIELDS; ++i) {
        if (i) out += ",";
        if (rx_field_type_at(i) == RX_FIELD_INT) {
            int32_t value;
            std::memcpy(&value, bytes + i * 4, 4);
            out += std::to_string(value);
        } else {
            float value;
            std::memcpy(&value, bytes + i * 4, 4);
            std::snprintf(buffer, sizeof(buffer), "%.9g", (double)value);
            out += buffer;
        }
    }
    out += "]";
}

void write_float(std::string &out, float v) {
    char buffer[64];
    std::snprintf(buffer, sizeof(buffer), "%.9g", (double)v);
    out += buffer;
}

rx_config make(void (*mutate)(rx_config &)) {
    rx_config c;
    rx_config_defaults(&c);
    if (mutate) mutate(c);
    rx_config_normalize(&c);
    return c;
}

} // namespace

int main(int argc, char **argv) {
    const char *path = (argc > 1) ? argv[1] : "geometry-golden.json";

    std::vector<Case> cases;
    cases.push_back({ "defaults", make(nullptr) });
    cases.push_back({ "no-outline", make([](rx_config &c) { c.outline_enabled = 0; }) });
    cases.push_back({ "wide-gap", make([](rx_config &c) { c.h_gap = 18.0f; c.v_gap = 18.0f; }) });
    cases.push_back({ "asymmetric", make([](rx_config &c) {
        c.h_length = 14.0f; c.v_length = 4.0f;
        c.h_thickness = 5.0f; c.v_thickness = 1.5f;
        c.h_gap = 2.0f; c.v_gap = 9.0f;
    }) });
    cases.push_back({ "t-shape", make([](rx_config &c) { c.t_shape = 1; }) });
    cases.push_back({ "dot-round", make([](rx_config &c) {
        c.dot_enabled = 1; c.dot_shape = RX_DOT_ROUND; c.dot_size = 5.0f;
        c.dot_inherit_color = 0; c.dot_color = rx_hex_to_rgb(0xFF3366u);
    }) });
    cases.push_back({ "rotated", make([](rx_config &c) { c.rotation = 37.5f; }) });
    cases.push_back({ "round-caps", make([](rx_config &c) { c.cap_style = RX_CAP_ROUND; }) });
    cases.push_back({ "tapered-caps", make([](rx_config &c) { c.cap_style = RX_CAP_TAPERED; }) });
    cases.push_back({ "scaled", make([](rx_config &c) { c.scale = 2.5f; }) });
    cases.push_back({ "dynamic-open", make([](rx_config &c) {
        c.dynamic_enabled = 1; c.dynamic_spread = 0.75f; c.dynamic_gap_boost = 12.0f;
    }) });
    cases.push_back({ "arms-off", make([](rx_config &c) {
        c.show_left = 0; c.show_top = 0; c.dot_enabled = 1;
    }) });
    cases.push_back({ "translucent", make([](rx_config &c) {
        c.opacity = 0.45f; c.outline_opacity = 0.3f;
    }) });
    cases.push_back({ "maxed", make([](rx_config &c) {
        c.scale = RX_MAX_SCALE; c.h_length = RX_MAX_LENGTH; c.v_length = RX_MAX_LENGTH;
        c.h_thickness = RX_MAX_THICKNESS; c.v_thickness = RX_MAX_THICKNESS;
        c.h_gap = RX_MAX_GAP; c.v_gap = RX_MAX_GAP;
        c.outline_thickness = RX_MAX_OUTLINE; c.dot_enabled = 1; c.dot_size = RX_MAX_DOT;
    }) });

    /* A slice of the randomizer's output space, so the wasm build has to agree
       on the generator as well as the geometry. */
    for (uint32_t seed : { 1u, 7u, 99u, 12345u, 987654u }) {
        rx_config c;
        rx_config_defaults(&c);
        rx_randomize(&c, seed, RX_RAND_ALL, RX_STYLE_ANY);
        static char names[8][32];
        static int index = 0;
        std::snprintf(names[index], sizeof(names[0]), "random-%u", seed);
        cases.push_back({ names[index], c });
        ++index;
    }

    std::string out;
    out.reserve(1 << 16);
    out += "{\n  \"note\": \"Generated by core/tests/fixture_writer.cpp - do not edit by hand.\",\n";
    char header[256];
    std::snprintf(header, sizeof(header),
                  "  \"abiVersion\": %d,\n  \"configSize\": %d,\n  \"configFields\": %d,\n"
                  "  \"shapeSize\": %d,\n  \"maxShapes\": %d,\n",
                  rx_abi_version(), rx_config_size(), rx_config_fields(),
                  rx_shape_size(), rx_max_shapes());
    out += header;
    out += "  \"fields\": [\n";
    for (int i = 0; i < RX_CONFIG_FIELDS; ++i) {
        out += "    { \"name\": \"";
        out += rx_field_name_at(i);
        out += "\", \"type\": ";
        out += (rx_field_type_at(i) == RX_FIELD_INT) ? "\"int\"" : "\"float\"";
        out += " }";
        if (i + 1 < RX_CONFIG_FIELDS) out += ",";
        out += "\n";
    }
    out += "  ],\n";
    out += "  \"cases\": [\n";

    for (size_t i = 0; i < cases.size(); ++i) {
        rx_geometry geo;
        const int32_t status = rx_build_geometry(&cases[i].config, &geo);
        out += "    {\n      \"name\": \"";
        out += cases[i].name;
        out += "\",\n      \"status\": ";
        out += std::to_string(status);
        out += ",\n      \"config\": ";
        write_config(out, cases[i].config);
        out += ",\n      \"fingerprint\": \"";
        char fp[32];
        std::snprintf(fp, sizeof(fp), "%016llx",
                      (unsigned long long)rx_config_fingerprint(&cases[i].config));
        out += fp;
        out += "\",\n      \"extent\": [";
        write_float(out, geo.extent_w);
        out += ",";
        write_float(out, geo.extent_h);
        out += "],\n      \"shapes\": [\n";
        for (int32_t s = 0; s < geo.count; ++s) {
            const rx_shape &sh = geo.shapes[s];
            out += "        [";
            const float values[10] = { sh.cx, sh.cy, sh.hw, sh.hh, sh.angle,
                                       sh.radius, sh.r, sh.g, sh.b, sh.a };
            for (int v = 0; v < 10; ++v) {
                if (v) out += ",";
                write_float(out, values[v]);
            }
            out += "," + std::to_string(sh.kind) + "," + std::to_string(sh.layer) + "]";
            if (s + 1 < geo.count) out += ",";
            out += "\n";
        }
        out += "      ]\n    }";
        if (i + 1 < cases.size()) out += ",";
        out += "\n";
    }
    out += "  ]\n}\n";

    std::FILE *f = std::fopen(path, "wb");
    if (!f) {
        std::fprintf(stderr, "fixture_writer: cannot open %s\n", path);
        return 1;
    }
    std::fwrite(out.data(), 1, out.size(), f);
    std::fclose(f);
    std::printf("fixture_writer: wrote %zu case(s) to %s\n", cases.size(), path);
    return 0;
}
